### ISSUE TITLE
动态页面的【正在直播】列表加强版现在刷新后直播标题全部消失

### ISSUE THREAD

**Issue by Notofnice** [tuntun0609/tun-bili-tool#85]
![image](https://github.com/tuntun0609/tun-bili-tool/assets/63146701/9740e7d7-999b-4127-bbc3-6ed7253d446f)

点击刷新后:
![image](https://github.com/tuntun0609/tun-bili-tool/assets/63146701/461fc3c4-6ac3-4da5-ab42-67aeaa0c5253)

浏览器:Chrome 117.0.5938.92
系统:Win10 22H2

**Comment by tuntun0609** [comment]
可能是b站网页更新了导致这个功能异常了，不过这个功能可以关闭了，因为b站原版已经改变了UI，默认展示全部正在直播了
